Flask_Database_05_11_2020_1589217223/mini_project_change/myproject/models.py
from myproject import db

class Item(db.Model):

    __tablename__ = 'items'
    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.Text)
    owner = db.relationship('Owner',backref='item',uselist=False)

    def __init__(self,name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Название {self.name} и ответственный (ая) - {self.owner.name}"
        else:
            return f"Название {self.name} и ответственного еще нет"

class Owner(db.Model):

    __tablename__ = 'owners'

    id = db.Column(db.Integer,primary_key= True)
    name = db.Column(db.Text)
    item_id = db.Column(db.Integer,db.ForeignKey('items.id'))

    def __init__(self,name,item_id):
        self.name = name
        self.item_id = item_id

    def __repr__(self):
        return f"Owner Name: {self.name}"

Flask_Database_05_11_2020_1589217223/mini_project_change/myproject/items/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):

    name = StringField('Имя')
    submit = SubmitField('Добавить задание, вещь ')

class DelForm(FlaskForm):

    id = IntegerField('ID Для удадения, задания, вещи')
    submit = SubmitField('Удалить')

Flask_Database_05_11_2020_1589217223/mini_project_change/myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):

    name = StringField('Имя ответственного :')
    item_id = IntegerField("Id вещи, задания: ")
    submit = SubmitField('Добавить ответственного')

Flask_Database_05_11_2020_1589217223/mini_project_change/myproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


app = Flask(__name__)


app.config['SECRET_KEY'] = 'mysecretkey'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:88888888@localhost/items'
# 'postgresql://postgres:88888888@localhost/items'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)


from myproject.items.views import items_blueprint
from myproject.owners.views import owners_blueprint

app.register_blueprint(owners_blueprint,url_prefix="/owners")
app.register_blueprint(items_blueprint,url_prefix='/items')

Flask_Database_05_11_2020_1589217223/mini_project_change/myproject/items/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.items.forms import AddForm,DelForm
from myproject.models import Item

items_blueprint = Blueprint('items',
                              __name__,
                              template_folder='templates/items')

@items_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data

        # Add new Item to database
        new_item = Item(name)
        db.session.add(new_item)
        db.session.commit()

        return redirect(url_for('items.list'))

    return render_template('add.html',form=form)

@items_blueprint.route('/list')
def list():
    # Grab a list of item from database.
    items = Item.query.all()
    return render_template('list.html', items=items)

@items_blueprint.route('/delete', methods=['GET', 'POST'])
def delete():

    form = DelForm()

    if form.validate_on_submit():
        id = form.id.data
        item = Item.query.get(id)
        db.session.delete(item)
        db.session.commit()

        return redirect(url_for('items.list'))
    return render_template('delete.html',form=form)

Flask_Database_05_11_2020_1589217223/mini_project_change/myproject/owners/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm

owners_blueprint = Blueprint('owners',
                              __name__,
                              template_folder='templates/owners')

@owners_blueprint.route('/add', methods=['GET', 'POST'])
def add():

    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        item_id = form.item_id.data
        # Add new owner to database
        new_owner = Owner(name,item_id)
        db.session.add(new_owner)
        db.session.commit()

        return redirect(url_for('items.list'))
    return render_template('add_owner.html',form=form)

Flask_Database_05_11_2020_1589217223/mini_project_change/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Adoption</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a>
      <a class="nav-item nav-link" href="{{ url_for('items.add') }}">Добавить </a>
      <a class="nav-item nav-link" href="{{ url_for('items.list') }}">Лист </a>
      <a class="nav-item nav-link" href="{{ url_for('items.delete') }}">Удалить</a>
      <a class="nav-item nav-link" href="{{ url_for('owners.add') }}">Добавить Пользователя</a>
    </div>

</nav>

    {% block content %}

    {% endblock %}
  </body>
</html>

Flask_Database_05_11_2020_1589217223/mini_project_change/myproject/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Добро пожаловать</h1>
</div>
{% endblock %}