flask_blueprints/social_news/models.py
from social_news import db,login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
# By inheriting the UserMixin we get access to a lot of built-in attributes
# which we will be able to call in our views!
# is_authenticated()
# is_active()
# is_anonymous()
# get_id()


# The user_loader decorator allows flask-login to load the current user
# and grab their id.

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):

    # Create a table in the db
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    # ----------------------------------------------------------

    profile_image = db.Column(db.String(20), nullable=False, default='default_profile.png')
    # -------------------------------------------------------------------

    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    # This connects NEws to a User Author.
    news = db.relationship('NewsItem', backref='author', lazy=True)

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        # https://stackoverflow.com/questions/23432478/flask-generate-password-hash-not-constant-output
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f"UserName: {self.username}"

class NewsItem(db.Model):
    # Setup the relationship to the User table
    __tablename__ = 'news_item'
    users = db.relationship(User)

    id = db.Column(db.Integer, primary_key=True)
    # Notice how we connect the NEws to a particular author
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    title = db.Column(db.String(140), nullable=False)
    text = db.Column(db.Text, nullable=False)

    def __init__(self, title, text, user_id):
        self.title = title
        self.text = text
        self.user_id =user_id


    def __repr__(self):
        return f"NEws Id: {self.id} --- Date: {self.date} --- Title: {self.title}"

flask_blueprints/social_news/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed

from social_news.models import User


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField("Login")


class RegistrationForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    username = StringField("Login", validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('password', message="Password not Equal")])
    pass_confirm = PasswordField("Confirm Password", validators=[DataRequired()])
    submit = SubmitField("Register")

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError("Email exists")

    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError("Username exists")


class UpdateUserForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    username = StringField("Login", validators=[DataRequired()])
    picture = FileField("Upload Picture", validators=[FileAllowed(['jpg', 'png', 'jpeg'])])

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError("Email exists")

    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError("Username exists")

flask_blueprints/social_news/__init__.py
from flask import Flask
import os
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SECRET_KEY'] = 'mysecretkey'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'


from social_news.core.views import core
from social_news.error_pages.handler import error_pages
from social_news.users.views import users

app.register_blueprint(error_pages)
app.register_blueprint(core)
app.register_blueprint(users)

flask_blueprints/social_news/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

flask_blueprints/social_news/users/views.py
from flask import render_template, url_for, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from social_news import db
from social_news.models import User, NewsItem
from social_news.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from social_news.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

@users.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods = ['GET', 'POST'])
def login():
    render_template("login.html")


#register
#login
#logout

flask_blueprints/social_news/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1 >Мой профиль {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>

</div>

{% endblock content %}

flask_blueprints/social_news/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <ul class="nav">

  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('core.info') }}">О нас</a>
  </li>
{#    {% if current_user.is_authenticated %}#}
{#    <li class="nav-link"><a href="{{ url_for('users.logout') }}">Выйти</a></li>#}
{#    <li class="nav-link"><a href="{{ url_for('users.account') }}">Мой аккаунт</a></li>#}
{#    <li class="nav-link"><a href="{{ url_for('news.create_news_item') }}">Добавить новость </a></li>#}
{#    {% else %}#}
{#    <li class="nav-link"><a href="{{ url_for('users.login') }}">Логин</a></li>#}
{#    <li class="nav-link"><a href="{{ url_for('users.register') }}">Регистрация</a></li>#}
{#    {% endif %}#}

</ul>
<div class="container">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

flask_blueprints/social_news/templates/create_news.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

flask_blueprints/social_news/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Welcome</h1>
    <p>Welcome</p>
  </div>

  <div class="container">


    {% for news_item in news.items %}
{##}
{#    <div class="card" >#}
{##}
{#      <div class="card-body">#}
{##}
{##}
{#        <h2><a class="card-title" href="  {{ url_for('news.news_item', news_item_id=news_item.id) }}">{{ news_item.title }}</a></h2>#}
{#        <a href="{{ url_for('users.user_news', username=news_item.author.username) }}">Written By: {{ news_item.author.username }}</a>#}
{#        <p>Published on: {{ news_item.date.strftime('%Y-%m-%d') }}</p>#}
{#        <p class="card-text">{{ news_item.text[:100] }}...</p>#}
{#        <a href="{{ url_for('news.news_item', news_item_id=news_item.id) }}" class="btn btn-primary">Read News</a>#}
{#      </div>#}
{#    </div>#}

   {% endfor %}

{#   <nav aria-label="Page navigation example">#}
{#     <ul class="pagination justify-content-center">#}
{#       {% for page_num in news.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}#}
{#          {% if news.page == page_num %}#}
{#          <li class="page-item disabled">#}
{#            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>#}
{#          </li>#}
{#          {% else %}#}
{#            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>#}
{#          {% endif %}#}
{#      {% endfor %}#}
{#    </nav>#}
{##}



{% endblock %}

flask_blueprints/social_news/templates/info.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Информационная страница</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

{% endblock %}

flask_blueprints/social_news/templates/login.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}
    {{ form.password.label }} {{ form.password() }}
    {{ form.submit() }}
</form>
{% endblock %}

flask_blueprints/social_news/templates/news_item.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ news_item.title }}</h1>
  <h2>Written by: {{news_item.author.username}}</h2>
  <h3>Published: {{ news_item.date.strftime('%B %d, %Y') }}</h3>
  <p>{{news_item.text}}</p>
   {% if news_item.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('news.update', news_item_id=news_item.id) }}">Обновить</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Удалить</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Удаление новоти </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Вы действительно хотите удалить ее ?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('news.delete_news_item', news_item_id=news_item.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

flask_blueprints/social_news/templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}<br>
    {{ form.username.label }} {{ form.username() }}<br>
    {{ form.password.label }} {{ form.password() }}<br>
    {{ form.pass_confirm.label }} {{ form.pass_confirm() }}<br>
    {{ form.submit() }}
</form>
{% endblock %}

flask_blueprints/social_news/templates/user_news.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% for news_item in news.items %}

          <h2><a href="{{ url_for('news.news_item', news_item=news_item.id) }}">{{ news_item.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_news', username=news_item.author.username) }}">{{ news_item.author.username }}</a>
          <p class="text-muted">Published on: {{ news_item.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{news_item.text}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in news.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if news.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_news', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_news', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}